# Generated by Django 3.0.4 on 2020-03-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterestQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend_word', models.CharField(max_length=50)),
                ('banana_score', models.IntegerField()),
                ('trend_score', models.IntegerField()),
                ('date_created', models.DateTimeField(verbose_name='date created')),
            ],
        ),
    ]
