# Generated by Django 3.0.4 on 2020-03-30 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20200330_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestquiz',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
